### ISSUE TITLE
Future Plans?

### ISSUE THREAD

**Issue by gingerbeardman** [canisbos/Quickscript#1]
I see you have deleted your website and twitter account.

I wondered if you had plans for Mojave/new Safari?

https://9to5mac.com/2018/06/09/safari-12-extensions-more/

If you do not wish to release your extensions through the App Store, I would be happy to release them on your behalf through my account?

**Comment by canisbos** [comment]
Hi Matt,

It's precisely because I don't want to spent the time and effort to port the extensions to the app extension framework that I decided to basically hide them from public view. They are open-source, and you have my blessing to take over any of them and port them or do whatever with them.

Best regards, 
Chul

**Comment by gingerbeardman** [comment]
Thank you. Very kind. 

I'm converting my own extensions right now, so I figured I'd see if I could "save" any of the other extensions that I use and rely on.
